# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/lpm_rom_irom/lpm_rom_irom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lpm_rom_irom || ORIG_REF_NAME==lpm_rom_irom} -quiet] -quiet
