# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a50tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/25Spring/Vivado_lab/projects/project_4/project_4.cache/wt [current_project]
set_property parent.project_path Z:/25Spring/Vivado_lab/projects/project_4/project_4.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/25Spring/Vivado_lab/projects/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files Z:/25Spring/Vivado_lab/lab4/coe/lab4/sc_datamem.coe
add_files Z:/25Spring/Vivado_lab/lab4/coe/lab4/lpm_rom_irom_io.coe
read_verilog -library xil_defaultlib {
  Z:/25Spring/Vivado_lab/lab1/src/alu.v
  Z:/25Spring/Vivado_lab/lab3/src/src/cla32.v
  Z:/25Spring/Vivado_lab/lab4/src/clock_and_mem_clock.v
  Z:/25Spring/Vivado_lab/lab3/src/src/dff32.v
  Z:/25Spring/Vivado_lab/lab4/src/display.v
  Z:/25Spring/Vivado_lab/lab2/src/immext.v
  Z:/25Spring/Vivado_lab/lab4/src/in_port.v
  Z:/25Spring/Vivado_lab/lab4/src/io_input.v
  Z:/25Spring/Vivado_lab/lab4/src/io_output.v
  Z:/25Spring/Vivado_lab/lab3/src/src/mux2x32.v
  Z:/25Spring/Vivado_lab/lab3/src/src/mux4x32.v
  Z:/25Spring/Vivado_lab/lab4/src/out_port_hex2dec.v
  Z:/25Spring/Vivado_lab/lab3/src/src/regfile.v
  Z:/25Spring/Vivado_lab/lab4/src/sc_computer_main.v
  Z:/25Spring/Vivado_lab/lab3/src/src/sc_cpu.v
  Z:/25Spring/Vivado_lab/lab2/src/sc_cu.v
  Z:/25Spring/Vivado_lab/lab4/src/sc_datamem.v
  Z:/25Spring/Vivado_lab/lab4/src/sc_instmem.v
  Z:/25Spring/Vivado_lab/lab4/src/seg7.v
  Z:/25Spring/Vivado_lab/lab4/src/sc_cpu_iotest.v
}
read_ip -quiet Z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram.xci
set_property used_in_implementation false [get_files -all z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram_ooc.xdc]

read_ip -quiet Z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_rom_irom/lpm_rom_irom.xci
set_property used_in_implementation false [get_files -all z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_rom_irom/lpm_rom_irom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/25Spring/Vivado_lab/lab4/constr/sc_computer_iotest.xdc
set_property used_in_implementation false [get_files Z:/25Spring/Vivado_lab/lab4/constr/sc_computer_iotest.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sc_cpu_iotest -part xc7a50tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sc_cpu_iotest.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sc_cpu_iotest_utilization_synth.rpt -pb sc_cpu_iotest_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
