# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram.xci
# IP: The module: 'lpm_ram_dq_dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lpm_ram_dq_dram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram.xci
# IP: The module: 'lpm_ram_dq_dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/25Spring/Vivado_lab/projects/project_4/project_4.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lpm_ram_dq_dram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
